import "./globals.css";
import styles from "./layout.css";
import type { Metadata } from "next";
import Provider from "./_component/Provider";
import { Noto_Sans_KR } from "next/font/google";

const FONT = Noto_Sans_KR({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="ko-KR">
      <body className={FONT.className}>
        <Provider>
          <div className={styles.layout}>{children}</div>
        </Provider>
      </body>
    </html>
  );
}
